apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: staging

  install:
    createNamespace: true
    remediation:
      retries: 3
      remediateLastFailure: true

  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      strategy: rollback
    failurePolicy: rollback
    cleanupOnFail: true

  rollback:
    recreate: true
    timeout: 5m
    disableWait: false

  chart:
    spec:
      chart: ./charts/nginx-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  values:
    replicaCount: 1
    image:
      repository: nginx
      tag: "1.29.3" # {"$imagepolicy": "flux-system:nginx-patch"}
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75
