apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-config
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/geeone/gitops-k8s-platform.git
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy-key
