apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: loki-stack
      version: "2.10.3"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      service:
        type: ClusterIP
    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki:3100/loki/api/v1/push
